// Explicitly reviewed title identities. Seasons split into parts in AniList are mapped below.
export const VIDEO_TITLES = {
  dandadan: { names: ['Дандадан', 'Дан Да Дан'] },
  frieren: { playlist: 355611, names: ['Провожающая в последний путь Фрирен', 'Фрирен'] },
  'jujutsu-kaisen': { playlist: 362167, names: ['Магическая битва'] },
  'chainsaw-man': { names: ['Человек-бензопила', 'Человек бензопила'] },
  'demon-slayer': { playlists: [700420], names: ['Клинок, рассекающий демонов', 'Клинок рассекающий демонов'] },
  'spy-family': { names: ['Семья шпиона', 'Семья шпионов'] },
  'attack-on-titan': { names: ['Атака титанов', 'Атака титана'] },
  'death-note': { names: ['Тетрадь смерти'] },
  'one-piece': { playlist: 931514, maxPages: 4, names: ['Ван-Пис', 'Ван Пис'] },
  haikyu: { playlist: 399342, names: ['Волейбол!!', 'Волейбол'] },
  'apothecary-diaries': { names: ['Монолог фармацевта'] },
  'solo-leveling': { playlist: 381054, names: ['Поднятие уровня в одиночку'] },
  'fullmetal-alchemist-brotherhood': { playlist: 342722, names: ['Стальной алхимик: Братство'] },
  'steins-gate': { names: ['Врата Штейна'] },
  'vinland-saga': { playlist: 1118179, names: ['Сага о Винланде'] },
  'mob-psycho-100': { names: ['Моб Психо 100'] },
  'bocchi-the-rock': { playlist: 585344, names: ['Одинокий рокер!', 'Одинокий рокер', 'Bocchi the Rock'] },
  'kaguya-sama': { playlist: 395557, names: ['Госпожа Кагуя: в любви как на войне', 'Госпожа Кагуя'] },
  'cyberpunk-edgerunners': { playlist: 331694, names: ['Киберпанк: Бегущие по краю'] },
  'oshi-no-ko': { names: ['Звёздное дитя', 'Звездное дитя', 'Ребёнок идола', 'Ребенок идола'] },
  'blue-lock': { names: ['Синяя тюрьма: Блю Лок', 'Синяя тюрьма', 'Блю Лок'] },
  'kaiju-no-8': { playlist: 609688, names: ['Кайдзю номер восемь', 'Кайдзю № 8', 'Кайдзю №8'] },
  'made-in-abyss': { playlist: 332952, names: ['Созданный в Бездне'] },
  're-zero': { names: ['Re:Zero', 'Жизнь с нуля в альтернативном мире'] },
  'tokyo-ghoul': { names: ['Токийский гуль'] },
  'code-geass': { playlist: 439045, names: ['Код Гиас: Восставший Лелуш', 'Код Гиас', 'Код Гиасс'] },
  'violet-evergarden': { playlist: 397295, names: ['Вайолет Эвергарден'] },
  'cowboy-bebop': { playlist: 341169, names: ['Ковбой Бибоп'] },
  evangelion: { playlist: 344210, names: ['Евангелион'] },
  'your-name': { names: ['Твоё имя', 'Твое имя'], movie: true },
  'a-silent-voice': { names: ['Форма голоса'], movie: true },
  suzume: { names: ['Судзумэ, закрывающая двери', 'Судзумэ', 'Судзуме'], movie: true },
  'spirited-away': { names: ['Унесённые призраками', 'Унесенные призраками'], movie: true },
  'princess-mononoke': { names: ['Принцесса Мононоке'], movie: true },
  'howls-moving-castle': { names: ['Ходячий замок'], movie: true },
}
